#!/usr/bin/env python3
import os
import sys
import struct

def build_bundle(input_dir, output_file):
    if not os.path.exists(input_dir):
        print(f"Error: Input directory '{input_dir}' does not exist.")
        sys.exit(1)

    # Gather all files in the assets folder recursively
    all_files = []
    for root, _, files in os.walk(input_dir):
        for file in files:
            full_path = os.path.join(root, file)
            # Store relative path so your game states can use keys like "audio/bgm.mp3"
            rel_path = os.path.relpath(full_path, input_dir).replace('\\', '/')
            all_files.append((full_path, rel_path))

    print(f"Packing {len(all_files)} assets into {output_file}...")

    with open(output_file, 'wb') as out:
        # 1. Write the 4-byte File Count (uint32_t)
        out.write(struct.pack('<I', len(all_files)))

        # 2. Iterate and write each file package entry
        for full_path, rel_path in all_files:
            file_size = os.path.getsize(full_path)
            
            # String name key (converted to UTF-8 bytes + trailing null byte)
            name_bytes = rel_path.encode('utf-8') + b'\x00'
            out.write(name_bytes)
            
            # 4-byte Payload Size (uint32_t)
            out.write(struct.pack('<I', file_size))
            
            # Raw binary data block payload
            with open(full_path, 'rb') as f:
                out.write(f.read())

    print("Bundle created successfully!")

def build_embedded_bundle(input_dir, output_cpp_file):
    if not os.path.exists(input_dir):
        print(f"Error: Input directory '{input_dir}' does not exist.")
        sys.exit(1)

    all_files = []
    for root, _, files in os.walk(input_dir):
        for file in files:
            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, input_dir).replace('\\', '/')
            all_files.append((full_path, rel_path))

    print(f"Packing {len(all_files)} assets into an embedded C++ array...")

    # Step 1: Pack the data structure into an in-memory bytearray
    bundle_data = bytearray()
    
    # Write the 4-byte File Count (uint32_t)
    bundle_data.extend(struct.pack('<I', len(all_files)))

    # Iterate and write each file entry
    for full_path, rel_path in all_files:
        file_size = os.path.getsize(full_path)
        
        # String name key (null-terminated UTF-8)
        name_bytes = rel_path.encode('utf-8') + b'\x00'
        bundle_data.extend(name_bytes)
        
        # 4-byte Payload Size (uint32_t)
        bundle_data.extend(struct.pack('<I', file_size))
        
        # Raw binary data block payload
        with open(full_path, 'rb') as f:
            bundle_data.extend(f.read())

    # Step 2: Write out the generated C++ implementation file
    with open(output_cpp_file, 'w', encoding='utf-8') as out:
        out.write("// Automatically generated by pack_assets.py. Do not modify manually.\n")
        out.write("#include <cstdint>\n#include <cstddef>\n\n")
        out.write("namespace RetroCore {\nnamespace Assets {\n\n")
        
        out.write(f"// Total raw payload size footprint in bytes\n")
        out.write(f"const size_t EMBEDDED_BUNDLE_SIZE = {len(bundle_data)};\n\n")
        
        out.write("const uint8_t EMBEDDED_BUNDLE_DATA[] = {\n")
        
        # Format bytes cleanly to keep compilation speeds manageable
        hex_lines = []
        for i in range(0, len(bundle_data), 12):
            chunk = bundle_data[i:i+12]
            hex_chunk = ", ".join(f"0x{b:02X}" for b in chunk)
            hex_lines.append("    " + hex_chunk)
            
        out.write(",\n".join(hex_lines))
        out.write("\n};\n\n")
        out.write("}\n}\n")

    print(f"Embedded array written successfully to '{output_cpp_file}' ({len(bundle_data)} bytes).")

if __name__ == "__main__":
    from pathlib import Path
    if len(sys.argv) < 3:
        print("Usage: python pack_assets.py <input_directory> <output_bundle_file>")
        sys.exit(1)

    file_extention = Path(sys.argv[2]).suffix
    if file_extention not in ['.bundle', '.cpp']:
        print("<output_bundle_file> should be .bundle or .cpp")
        sys.exit(1)

    if file_extention == '.bundle':
        build_bundle(sys.argv[1], sys.argv[2])
    else:
        build_embedded_bundle(sys.argv[1], sys.argv[2])

